#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  7 13:36:35 2019

@author: aydinj
"""

s = 'azcbobobegghakl'
pattern = 'bob'
count = 0

for i in range(0, len(s)-2):
    if s[i] + s[i+1] + s[i+2] == pattern:
        count+=1
print('Number of time bob occurs is: {}'.format(count))
count = 0