#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 12 22:06:42 2019

@author: aydinj
"""

balance = 4773
annualInterestRate = 0.2
minimumFixedMonthlyPayment = 10
monthlyInterestRate = annualInterestRate/12.0
monthlyUnpaidBalance = balance - minimumFixedMonthlyPayment
updatedBalanceEachMonth = monthlyUnpaidBalance + monthlyInterestRate * monthlyUnpaidBalance 

while updatedBalanceEachMonth > 0:
    for i in range(12):
        updatedBalanceEachMonth = monthlyUnpaidBalance + monthlyInterestRate * monthlyUnpaidBalance
        monthlyUnpaidBalance = updatedBalanceEachMonth - minimumFixedMonthlyPayment
        #print(f'Monthly Unpaid Balance: {monthlyUnpaidBalance}')
        #print(f'Updated Balance each Month: {updatedBalanceEachMonth}')
    if updatedBalanceEachMonth > 0:
        updatedBalanceEachMonth = balance
        minimumFixedMonthlyPayment += 10
        monthlyUnpaidBalance = updatedBalanceEachMonth - minimumFixedMonthlyPayment
        #print(f'Updated Balance Each Month: {updatedBalanceEachMonth}, Minimum Fixed Monthly Payment: {minimumFixedMonthlyPayment}')

print(f'Lowest Payment: {minimumFixedMonthlyPayment}')