#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  7 20:19:47 2019

@author: aydinj
"""

s = 'asjkdbakjsbajlbs'
longest = ''
for i in range(len(s)):
    temp_longest = s[i]
    for j in range(i+1, len(s)):
        if ord(s[i]) <= ord(s[j]):
            temp_longest += s[j]
            i+=1
        else:
            break
        if len(temp_longest) > len(longest):
            longest = temp_longest
print(longest)