#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  3 17:01:51 2019

@author: aydinj
"""

s = 'Aydin'
vowels = ['a', 'e', 'i', 'o', 'u']
count = 0

for i in range(len(s)):
   while s[i].lower() in vowels:
       print(s[i])
       count +=1
       break
print(f'Number of vowels: {count}')